# 应用启动端口
server:
  port: 8083

# debug 细粒度日志打印
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

# spring cloud gateway
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/**

# dubbo
dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

#      routes:
#        - id: add_request_header_route
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/name/**
#          filters:
#            - AddRequestHeader=clarity, clarity
# 路由举例
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: after_route1
#          uri: http://localhost:8082/api
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]